// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdzdkatqmhnrhytddfgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkemRrYXRxbWhucmh5dGRkZmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTU0OTQsImV4cCI6MjA2MjM3MTQ5NH0.tno598YlBiVLkd23brq1MdcxxYPWev0zs7xXDJ0eCeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);